-- mysql script generated by mysql workbench
-- mon jan 13 22:29:58 2020
-- model: new model    version: 1.0
-- mysql workbench forward engineering

set @old_unique_checks=@@unique_checks, unique_checks=0;
set @old_foreign_key_checks=@@foreign_key_checks, foreign_key_checks=0;
set @old_sql_mode=@@sql_mode, sql_mode='only_full_group_by,strict_trans_tables,no_zero_in_date,no_zero_date,error_for_division_by_zero,no_engine_substitution';

-- -----------------------------------------------------
-- schema beutylab
-- -----------------------------------------------------
/*drop schema if exists `beutylab` ;

-- -----------------------------------------------------
-- schema beutylab
-- -----------------------------------------------------
create schema if not exists `beutylab` default character set utf8 ;*/
use `beutylab` ;

-- -----------------------------------------------------
-- table `paises`
-- -----------------------------------------------------
-- drop table if exists `paises` ;

create table if not exists `paises` (
  `id_pais` int not null,
  `nombre` varchar(45) null,
  primary key (`id_pais`))
engine = innodb;


-- -----------------------------------------------------
-- table `tipos_identificacion`
-- -----------------------------------------------------
-- drop table if exists `tipos_identificacion` ;

create table if not exists `tipos_identificacion` (
  `id_tipo_id` int not null,
  `short_name` varchar(10) null,
  `descripcion` varchar(50) null,
  `tipos_identificacioncol` varchar(45) null,
  primary key (`id_tipo_id`))
engine = innodb;


-- -----------------------------------------------------
-- table `usuarios`
-- -----------------------------------------------------
-- drop table if exists `usuarios` ;

create table if not exists `usuarios` (
  `id_usuario` int not null AUTO_INCREMENT,
  `nombres` varchar(200) not null,
  `apellidos` varchar(200) null,
  `email` varchar(100) not null,
    email_verified_at datetime null,
  `movil` varchar(50) null,
  `direccion` varchar(45) null,
  `identificacion` varchar(50) null,
  `id_pais` int null,
  `id_tipo_id` int null,
  `username` varchar(100) null,
  `password` varchar(100) null,
  `estado` varchar(1) null,
  `fec_registro` datetime null default current_timestamp(),
  `fecha_cumpleanos` date null,
  `ciudad` varchar(200) null,
  `img_perfil` varchar(200) null,
  `nombre_contacto` varchar(100) null,
  `telefono_contacto` varchar(100) null,
  `rh` varchar(1) null,
  primary key (`id_usuario`),
  index `fk_personas_paises1_idx` (`id_pais` asc),
  index `fk_personas_tipos_identificacion1_idx` (`id_tipo_id` asc),
  constraint `fk_personas_paises1`
    foreign key (`id_pais`)
    references `paises` (`id_pais`)
    on delete no action
    on update no action,
  constraint `fk_personas_tipos_identificacion1`
    foreign key (`id_tipo_id`)
    references `tipos_identificacion` (`id_tipo_id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `medicos`
-- -----------------------------------------------------
-- drop table if exists `medicos` ;

create table if not exists `medicos` (
  `id_medico` int not null,
  `presentacion` varchar(4000) null,
  `img_perfil` varchar(2000) null,
  `id_usuario` int not null,
  primary key (`id_medico`),
  index `fk_medicos_usuarios1_idx` (`id_usuario` asc),
  constraint `fk_medicos_usuarios1`
    foreign key (`id_usuario`)
    references `usuarios` (`id_usuario`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `estudios`
-- -----------------------------------------------------
-- drop table if exists `estudios` ;

create table if not exists `estudios` (
  `id_estudio` int not null,
  `universidad` varchar(300) null,
  `fecha_inicio` date null,
  `fecha_fin` date null,
  `titulo` varchar(300) null,
  `id_medico` int not null,
  primary key (`id_estudio`),
  index `fk_estudios_medicos1_idx` (`id_medico` asc),
  constraint `fk_estudios_medicos1`
    foreign key (`id_medico`)
    references `medicos` (`id_medico`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `consultorios`
-- -----------------------------------------------------
-- drop table if exists `consultorios` ;

create table if not exists `consultorios` (
  `id_consultorio` int not null,
  `direccion` varchar(100) null,
  `telefono` varchar(45) null,
  `descripcion` varchar(100) not null,
  `consultorioscol` varchar(45) not null,
  `id_medico` int not null,
  primary key (`id_consultorio`, `descripcion`, `consultorioscol`),
  index `fk_consultorios_medicos1_idx` (`id_medico` asc),
  constraint `fk_consultorios_medicos1`
    foreign key (`id_medico`)
    references `medicos` (`id_medico`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `experiencia_laboral`
-- -----------------------------------------------------
-- drop table if exists `experiencia_laboral` ;

create table if not exists `experiencia_laboral` (
  `id_experienci` int not null,
  `cargo` varchar(200) null,
  `entidad` varchar(200) null,
  `fecha_inicio` date null,
  `fecha_fin` date null,
  `id_medico` int not null,
  primary key (`id_experienci`),
  index `fk_experiencia_laboral_medicos1_idx` (`id_medico` asc),
  constraint `fk_experiencia_laboral_medicos1`
    foreign key (`id_medico`)
    references `medicos` (`id_medico`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `habtaciones`
-- -----------------------------------------------------
-- drop table if exists `habtaciones` ;

create table if not exists `habtaciones` (
  `id_habitacion` int not null,
  `nombre` varchar(100) null,
  `comodidades` varchar(2000) null,
  `precio_noche` double null,
  `estado` varchar(1) null,
  primary key (`id_habitacion`))
engine = innodb;


-- -----------------------------------------------------
-- table `habitaciones_img`
-- -----------------------------------------------------
-- drop table if exists `habitaciones_img` ;

create table if not exists `habitaciones_img` (
  `id_habitacion_img` int not null,
  `img` varchar(200) null,
  `id_habitacion` int not null,
  primary key (`id_habitacion_img`),
  index `fk_habitaciones_img_habtaciones1_idx` (`id_habitacion` asc),
  constraint `fk_habitaciones_img_habtaciones1`
    foreign key (`id_habitacion`)
    references `habtaciones` (`id_habitacion`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `procedimientos`
-- -----------------------------------------------------
-- drop table if exists `procedimientos` ;

create table if not exists `procedimientos` (
  `id_procedimiento` int not null,
  `nombre` varchar(200) null,
  `descripcion` varchar(500) null,
  `precio` double null,
  primary key (`id_procedimiento`))
engine = innodb;


-- -----------------------------------------------------
-- table `cotizaciones`
-- -----------------------------------------------------
-- drop table if exists `cotizaciones` ;

create table if not exists `cotizaciones` (
  `id_cotizacion` int not null,
  `fec_registro` date null,
  `estado` varchar(1) null,
  `valor` double null,
  `fecha_procedimiento` date null,
  `id_habitacion` int not null,
  `id_usuario` int not null,
  primary key (`id_cotizacion`),
  index `fk_cotizaciones_habtaciones1_idx` (`id_habitacion` asc),
  index `fk_cotizaciones_usuarios1_idx` (`id_usuario` asc),
  constraint `fk_cotizaciones_habtaciones1`
    foreign key (`id_habitacion`)
    references `habtaciones` (`id_habitacion`)
    on delete no action
    on update no action,
  constraint `fk_cotizaciones_usuarios1`
    foreign key (`id_usuario`)
    references `usuarios` (`id_usuario`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `cotizaciones_x_procedimiento`
-- -----------------------------------------------------
-- drop table if exists `cotizaciones_x_procedimiento` ;

create table if not exists `cotizaciones_x_procedimiento` (
  `id_cotizacion` int not null,
  `id_cirujia` int not null,
  index `fk_cotizaciones_x_cirujia_cotizaciones1_idx` (`id_cotizacion` asc),
  index `fk_cotizaciones_x_cirujia_cirujias1_idx` (`id_cirujia` asc),
  primary key (`id_cotizacion`, `id_cirujia`),
  constraint `fk_cotizaciones_x_cirujia_cotizaciones1`
    foreign key (`id_cotizacion`)
    references `cotizaciones` (`id_cotizacion`)
    on delete no action
    on update no action,
  constraint `fk_cotizaciones_x_cirujia_cirujias1`
    foreign key (`id_cirujia`)
    references `procedimientos` (`id_procedimiento`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `planes`
-- -----------------------------------------------------
-- drop table if exists `planes` ;

create table if not exists `planes` (
  `id_plan` int not null,
  `nombre` varchar(100) null,
  `descripcion` varchar(500) null,
  `valor` double null,
  `img_plan` varchar(200) null,
  `id_habitacion` int not null,
  primary key (`id_plan`),
  index `fk_planes_habtaciones1_idx` (`id_habitacion` asc),
  constraint `fk_planes_habtaciones1`
    foreign key (`id_habitacion`)
    references `habtaciones` (`id_habitacion`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `plan_x_procedimientos`
-- -----------------------------------------------------
-- drop table if exists `plan_x_procedimientos` ;

create table if not exists `plan_x_procedimientos` (
  `id_plan` int not null,
  `id_procedimiento` int not null,
  index `fk_plan_x_procedimientos_planes1_idx` (`id_plan` asc),
  index `fk_plan_x_procedimientos_procedimientos1_idx` (`id_procedimiento` asc),
  primary key (`id_plan`, `id_procedimiento`),
  constraint `fk_plan_x_procedimientos_planes1`
    foreign key (`id_plan`)
    references `planes` (`id_plan`)
    on delete no action
    on update no action,
  constraint `fk_plan_x_procedimientos_procedimientos1`
    foreign key (`id_procedimiento`)
    references `procedimientos` (`id_procedimiento`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `usuarios_img_zona_afectada`
-- -----------------------------------------------------
-- drop table if exists `usuarios_img_zona_afectada` ;

create table if not exists `usuarios_img_zona_afectada` (
  `id_imagen` int not null,
  `imagen` varchar(2000) null,
  `id_usuario` int not null,
  primary key (`id_imagen`),
  index `fk_usuarios_img_zona_afectada_usuarios1_idx` (`id_usuario` asc),
  constraint `fk_usuarios_img_zona_afectada_usuarios1`
    foreign key (`id_usuario`)
    references `usuarios` (`id_usuario`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `observaciones_medicas`
-- -----------------------------------------------------
-- drop table if exists `observaciones_medicas` ;

create table if not exists `observaciones_medicas` (
  `id_observacion_medica` int not null,
  `id_tipo_observacion` int not null comment 'este campo contiene el tipo de observaci�n medica.\n1. enfermada\n2. alergia\n3. procedimiento anterior',
  `descripcion` varchar(45) null,
  primary key (`id_observacion_medica`))
engine = innodb;


-- -----------------------------------------------------
-- table `usuarios_observaciones_medica`
-- -----------------------------------------------------
-- drop table if exists `usuarios_observaciones_medica` ;

create table if not exists `usuarios_observaciones_medica` (
  `usuarios_id_usuario` int not null,
  `id_observacion_medica` int not null,
  index `fk_usuarios_observaciones_medica_usuarios1_idx` (`usuarios_id_usuario` asc),
  index `fk_usuarios_observaciones_medica_observaciones_medicas1_idx` (`id_observacion_medica` asc),
  primary key (`usuarios_id_usuario`, `id_observacion_medica`),
  constraint `fk_usuarios_observaciones_medica_usuarios1`
    foreign key (`usuarios_id_usuario`)
    references `usuarios` (`id_usuario`)
    on delete no action
    on update no action,
  constraint `fk_usuarios_observaciones_medica_observaciones_medicas1`
    foreign key (`id_observacion_medica`)
    references `observaciones_medicas` (`id_observacion_medica`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `reservas`
-- -----------------------------------------------------
-- drop table if exists `reservas` ;

create table if not exists `reservas` (
  `id_reserva` int not null,
  `fecha_reserva` datetime null,
  `observaciones` varchar(200) null,
  `estado` int null,
  `id_cotizacion` int not null,
  `id_plan` int not null,
  `id_usuario` int not null,
  primary key (`id_reserva`),
  index `fk_reservas_cotizaciones1_idx` (`id_cotizacion` asc),
  index `fk_reservas_planes1_idx` (`id_plan` asc),
  index `fk_reservas_usuarios1_idx` (`id_usuario` asc),
  constraint `fk_reservas_cotizaciones1`
    foreign key (`id_cotizacion`)
    references `cotizaciones` (`id_cotizacion`)
    on delete no action
    on update no action,
  constraint `fk_reservas_planes1`
    foreign key (`id_plan`)
    references `planes` (`id_plan`)
    on delete no action
    on update no action,
  constraint `fk_reservas_usuarios1`
    foreign key (`id_usuario`)
    references `usuarios` (`id_usuario`)
    on delete no action
    on update no action)
engine = innodb;


set sql_mode=@old_sql_mode;
set foreign_key_checks=@old_foreign_key_checks;
set unique_checks=@old_unique_checks;
